# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-03 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0005_teacherfile'),
        ('school', '0005_school_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('rule', models.CharField(choices=[('Y', 'year'), ('M', 'month'), ('W', 'week'), ('D', 'day')], max_length=1)),
                ('end_recurring_period', models.DateTimeField(blank=True, null=True)),
                ('cls', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Cls')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('original_start', models.DateTimeField(blank=True, null=True)),
                ('original_end', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ScheduleEvent')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherProfile')),
            ],
        ),
    ]
