# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-03 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='weekday',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
