# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-04 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_scheduleevent_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleoccurrence',
            name='is_attend_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleoccurrence',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
