# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-05 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191204_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='created_time',
            field=models.DateTimeField(),
        ),
    ]
