# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-06 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_school_img'),
        ('schedule', '0004_auto_20191205_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleoccurrence',
            name='cls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Cls'),
        ),
    ]
