# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-06 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_scheduleoccurrence_cls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleoccurrence',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.ScheduleEvent'),
        ),
    ]
