# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-10-29 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrecord',
            name='stats',
            field=models.TextField(default='{}', max_length=2000),
        ),
    ]
