# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-08-07 02:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '__first__'),
        ('quiz', '__first__'),
        ('teacher', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=200, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('info', models.TextField(blank=True, max_length=200, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentKnowledgeAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_space_graph_uri', models.TextField(blank=True, max_length=100, null=True)),
                ('learning_router_uri', models.TextField(blank=True, max_length=100, null=True)),
                ('assessment_report_uri', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentKnowledgeVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vector_uri', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('phone', models.CharField(db_index=True, max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('age', models.IntegerField(default=15)),
                ('info', models.TextField(default='', max_length=2000)),
                ('clss', models.ManyToManyField(blank=True, to='school.Cls')),
                ('teachers', models.ManyToManyField(blank=True, to='teacher.TeacherProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuizRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('stats', models.TextField(blank=True, max_length=1000, null=True)),
                ('quiz_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizRecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReportPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_uri', models.CharField(max_length=150)),
                ('html_uri', models.CharField(max_length=150)),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('datetime', models.DateField(blank=True, null=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentProfile')),
            ],
        ),
        migrations.AddField(
            model_name='questionrecord',
            name='student_quiz_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentQuizRecord'),
        ),
    ]
