# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-08-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190809_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
