# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-08-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofile_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
