# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-08-23 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190822_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='student_imgs'),
        ),
    ]
