# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-12 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190823_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreportpaper',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
