# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-16 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190916_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentknowledgevector',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='student.StudentProfile'),
        ),
    ]
