# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-16 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_studentknowledgevector_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentKnowledgeVectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vectors', models.TextField(blank=True, max_length=20000, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='student.StudentProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentknowledgevector',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentKnowledgeVector',
        ),
    ]
