# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-10-25 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_studentquizrecord_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizrecord',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.StudentProfile'),
            preserve_default=False,
        ),
    ]
