# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-10-31 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20191029_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='grade',
            field=models.IntegerField(default=9),
        ),
    ]
