# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-11 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver', models.CharField(max_length=100)),
                ('msg', models.TextField(max_length=1000)),
                ('msg_type', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
