# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='grade_no',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='textbook',
            name='half',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
