# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-11 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0002_auto_20190911_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='textbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='textbook.Textbook'),
        ),
        migrations.AlterField(
            model_name='part',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='textbook.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='textbook.Chapter'),
        ),
    ]
