# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-10-17 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0003_auto_20190911_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
