# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-08-09 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('student', '0002_auto_20190809_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=1)),
                ('resources', models.TextField(default='{}', max_length=500)),
                ('remaining_resources', models.TextField(default='{}', max_length=500)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(db_index=True, max_length=20)),
                ('info', models.CharField(default='{}', max_length=500)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Cls')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('resources', models.TextField(default='{}', max_length=500)),
                ('default_price', models.IntegerField(default=1)),
                ('subject', models.CharField(db_index=True, max_length=20)),
                ('info', models.CharField(default='{}', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=1)),
                ('payment_record', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('resources', models.TextField(default='{}', max_length=500)),
                ('remaining_resources', models.TextField(default='{}', max_length=500)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(db_index=True, max_length=20)),
                ('info', models.CharField(default='{}', max_length=500)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Plan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentProfile')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.PlanTemplate'),
        ),
    ]
