# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-08-23 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantemplate',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
