# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-08-27 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190822_1106'),
        ('plan', '0002_plantemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentplan',
            name='cls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Cls'),
        ),
    ]
