# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-12 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_school_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='school_imgs'),
        ),
    ]
