# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-08-09 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='subject_icons'),
        ),
    ]
