# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-08-11 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_space', '0002_subject_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorreason',
            old_name='descritpion',
            new_name='description',
        ),
    ]
