# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-16 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190912_1453'),
        ('student', '0006_studentreportpaper_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=200, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('info', models.TextField(blank=True, max_length=200, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentProfile')),
                ('student_quiz_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentQuizRecord')),
            ],
        ),
        migrations.RemoveField(
            model_name='questionrecord',
            name='option',
        ),
        migrations.RemoveField(
            model_name='questionrecord',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionrecord',
            name='student_quiz_record',
        ),
        migrations.DeleteModel(
            name='QuestionRecord',
        ),
    ]
