# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-16 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20190916_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentknowledgevector',
            name='graph_id',
        ),
        migrations.RemoveField(
            model_name='studentknowledgevector',
            name='vector_uri',
        ),
        migrations.AddField(
            model_name='studentknowledgevector',
            name='vector',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
