# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-10-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_studentquizrecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquizrecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentProfile'),
        ),
    ]
