# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-11 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_school_phone'),
        ('student', '0017_studentprofile_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls_no', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('expired', models.BooleanField(default=False)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Cls')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentProfile')),
            ],
        ),
    ]
