# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-12 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_tuition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuition',
            old_name='cls_no',
            new_name='remaining_no',
        ),
        migrations.AddField(
            model_name='tuition',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
