# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-08-30 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_quiz_type'),
        ('teacher', '0002_teacherprofile_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(blank=True, null=True, to='quiz.Question')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherProfile')),
            ],
        ),
    ]
