# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-10-25 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_imgs'),
        ),
    ]
