# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-11 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacherprofile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='teacher_imgs/files')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherProfile')),
            ],
        ),
    ]
