# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-08-10 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190808_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(default='suitang', max_length=20),
        ),
    ]
