# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-10-02 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190912_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_records', to='student.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='quizrecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherProfile'),
        ),
    ]
