# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-10-11 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20191002_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
