# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-04 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quizrecord_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='analysis_img',
            field=models.ImageField(blank=True, null=True, upload_to='analysis_imgs'),
        ),
    ]
