# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-12 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_analysis_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='authenticated',
            field=models.CharField(default='U', max_length=5),
        ),
    ]
