# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-27 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_space', '0003_auto_20190811_1650'),
        ('quiz', '0011_auto_20191112_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=100)),
                ('error_reason', models.ManyToManyField(blank=True, to='knowledge_space.ErrorReason')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompletionAnswer', to='quiz.Question')),
            ],
        ),
    ]
