# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-03 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_completionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='single-choice', max_length=20),
        ),
    ]
